Update the docs for the openai example with the right running script
The previous instructions to run the OpenAI sample were resulting in the error

```
error: could not find `Cargo.toml` in `stepflow-main` or any parent directory
```

To resolve this, we can provide the path to Cargo.toml which is in the `stepflow-rs` directory.